export interface Database {
  public: {
    Tables: {
      websites: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          url: string;
          domain: string | null;
          vapid_public_key: string | null;
          vapid_private_key: string | null;
          notifications_sent: number;
          active_subscribers: number;
          status: 'active' | 'paused' | 'deleted';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          url: string;
          domain?: string | null;
          vapid_public_key?: string | null;
          vapid_private_key?: string | null;
          notifications_sent?: number;
          active_subscribers?: number;
          status?: 'active' | 'paused' | 'deleted';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          url?: string;
          domain?: string | null;
          vapid_public_key?: string | null;
          vapid_private_key?: string | null;
          notifications_sent?: number;
          active_subscribers?: number;
          status?: 'active' | 'paused' | 'deleted';
          created_at?: string;
          updated_at?: string;
        };
      };
      subscribers: {
        Row: {
          id: string;
          website_id: string;
          endpoint: string | null;
          p256dh_key: string | null;
          auth_key: string | null;
          fcm_token: string | null;
          platform: 'web' | 'android' | 'ios';
          browser: string | null;
          os: string | null;
          device_type: string | null;
          country: string | null;
          city: string | null;
          ip_address: string | null;
          user_agent: string | null;
          status: 'active' | 'inactive' | 'blocked';
          subscribed_at: string;
          last_seen_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          website_id: string;
          endpoint?: string | null;
          p256dh_key?: string | null;
          auth_key?: string | null;
          fcm_token?: string | null;
          platform?: 'web' | 'android' | 'ios';
          browser?: string | null;
          os?: string | null;
          device_type?: string | null;
          country?: string | null;
          city?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          status?: 'active' | 'inactive' | 'blocked';
          subscribed_at?: string;
          last_seen_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          website_id?: string;
          endpoint?: string | null;
          p256dh_key?: string | null;
          auth_key?: string | null;
          fcm_token?: string | null;
          platform?: 'web' | 'android' | 'ios';
          browser?: string | null;
          os?: string | null;
          device_type?: string | null;
          country?: string | null;
          city?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          status?: 'active' | 'inactive' | 'blocked';
          subscribed_at?: string;
          last_seen_at?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      campaigns: {
        Row: {
          id: string;
          website_id: string;
          name: string;
          title: string;
          body: string;
          icon_url: string | null;
          image_url: string | null;
          click_url: string | null;
          actions: any | null;
          status: 'draft' | 'scheduled' | 'sending' | 'completed' | 'failed' | 'paused';
          scheduled_for: string | null;
          sent_at: string | null;
          sent_count: number;
          failed_count: number;
          click_count: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          website_id: string;
          name: string;
          title: string;
          body: string;
          icon_url?: string | null;
          image_url?: string | null;
          click_url?: string | null;
          actions?: any | null;
          status?: 'draft' | 'scheduled' | 'sending' | 'completed' | 'failed' | 'paused';
          scheduled_for?: string | null;
          sent_at?: string | null;
          sent_count?: number;
          failed_count?: number;
          click_count?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          website_id?: string;
          name?: string;
          title?: string;
          body?: string;
          icon_url?: string | null;
          image_url?: string | null;
          click_url?: string | null;
          actions?: any | null;
          status?: 'draft' | 'scheduled' | 'sending' | 'completed' | 'failed' | 'paused';
          scheduled_for?: string | null;
          sent_at?: string | null;
          sent_count?: number;
          failed_count?: number;
          click_count?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      notification_logs: {
        Row: {
          id: string;
          campaign_id: string | null;
          subscriber_id: string;
          website_id: string;
          status: 'sent' | 'failed' | 'delivered' | 'clicked' | 'dismissed';
          platform: string | null;
          error_message: string | null;
          sent_at: string | null;
          delivered_at: string | null;
          clicked_at: string | null;
          dismissed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          campaign_id?: string | null;
          subscriber_id: string;
          website_id: string;
          status: 'sent' | 'failed' | 'delivered' | 'clicked' | 'dismissed';
          platform?: string | null;
          error_message?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          clicked_at?: string | null;
          dismissed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string | null;
          subscriber_id?: string;
          website_id?: string;
          status?: 'sent' | 'failed' | 'delivered' | 'clicked' | 'dismissed';
          platform?: string | null;
          error_message?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          clicked_at?: string | null;
          dismissed_at?: string | null;
          created_at?: string;
        };
      };
    };
  };
}
